---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: StorageGRID のドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: 既知の問題
      url: "/reference-known-issues.html"
  - title: はじめに
    entries:
    - title: StorageGRID システムを検出
      url: "/task-discover-storagegrid.html"
  - title: StorageGRID システムを管理
    entries:
    - title: StorageGRID システムを表示します
      url: "/task-view-storagegrid.html"
    - title: StorageGRID証明書の表示と更新
      url: "/task-manage-certificates.html"
    - title: アドバンストビューを使用したStorageGRIDの管理
      url: task-administer-storagegrid.html
    - title: ネットアップのデータサービスとStorageGRID を併用
      url: "/task-enable-data-services.html"
    - title: 作業環境を削除します
      url: "/task-remove-storagegrid.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
